config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions',
        passwords: 'users/passwords'
        }

  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :carts
  resources :history_address
  resources :admin_users, only:[:index]
  get "/add/disc" => "items#add_disc"
  get "/add/song" => "items#add_song"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy] do
    resources :discs
    resources :songs

    resources :categories,only: [:new, :create, :index, :update, :edit, :destroy] do
    end

  end
  root "items#index"
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	has_many :discs, dependent: :destroy
	has_many :histories
	has_many :carts
	#belongs_to :category

	attr_accessor :disc_name, :number, :song_name

 	accepts_nested_attributes_for :discs


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/show.html.erb
<div class="user-box"><i class="fa fa-user-circle" aria-hidden="true"><p class="title1">ユーザー情報</p></i><br>
<!-- ユーザー情報の一覧 -->
 <div class="user-text">
  <span class="user_logo">カナ</span> 　<%= "#{@user.kana_lastname} #{@user.kana_firstname}" %><br>
  <span class="user_logo">名前</span> 　<%= "#{@user.lastname} #{@user.firstname}" %><br>
  <span class="user_logo">メールアドレス</span> 　<%= @user.email %><br>
  <span class="user_logo">郵便番号</span> 　<%= @user.postal_code %><br>
  <span class="user_logo">住所</span> 　<%= @user.address %><br>
  <span class="user_logo">電話番号</span> 　<%= @user.phone %><br>
  <!-- プロフィール編集&削除ボタン -->
    <%= link_to "削除", users_destroy_path,method: :delete ,class: "square_btn2",data: { :confirm => "ユーザーを削除しますか？\n削除すると戻せませんのでご注意ください。"}%>
    <%= link_to "編集", edit_user_registration_path ,class: "square_btn1"%>
</div></div></div>


<!-- 購入履歴情報 -->
<div class="history-box"><i class="fa fa-history" aria-hidden="true"><p class="title1">購入履歴</p></i>
  <div class="history-text">
    <% @history_ids.each do |i| %> <!-- コントローラーでhistory_address_idを抽出して@history_idsへ配列で格納 -->
      <% h_histories = @histories.where(history_address_id: i) #history_addressで抽出した履歴一覧%>
      <% h_history_first = h_histories.first #住所、日時表示のため、うち一番上のレコードを抽出%>
      <% h_histries_count = 0 %>
      <% h_histories.each {|h_h_item| h_histries_count += h_h_item.count}%>

      <p>購入日：<%= h_history_first.created_at.strftime('%Y/%m/%d %H:%M')  %>　<span><%= h_history_first.order_status_i18n%></span></p>
        <div class="adress-text">
          【送付先情報】<br>
          <p><%= h_history_first.history_address.postal_code%>  <%= h_history_first.history_address.address %></p>
            名前 : <%= h_history_first.history_address.lastname%>  <%= h_history_first.history_address.firstname%>   (電話番号 : <%= h_history_first.history_address.phone%>) <br>
        </div>

        購入商品：<%= h_histories.size %>（購入点数：<%= h_histries_count %> ）<br>
        <table>
          <tr>
            <td class="history_items_name">アルバム</td>
            <td class="history_items_name">アーティスト</td>
            <td>値段</td>
            <td>数</td>
            <td>小計</td>
          </tr>

          <% h_histories.each do |h_h_item| #history_addressで抽出した履歴一覧から個別出力%>
          <tr>
            <td><%= h_h_item.item.item_name %></td>
            <td><%= h_h_item.item.artist_name %></td>
            <td><%= h_h_item.price %></td>
            <td> ×<%= h_h_item.count%> =</td>
            <td><%= h_total_price = h_h_item.price * h_h_item.count %></td>
          </tr>
          <% @total_price += h_total_price%>
          <% end %>

          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>送料：</td>
            <td>540</td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>合計：</td>
            <td><%= @total_price + 540%></td>
          </tr>

        </table>
          <% @total_price = 0 #total_price初期化%>
          <br>
          <hr>
          <br>
        <% end %>
        <!-- 送付先 -->
  </div>
</div>
<!-- paginationの設定 -->
 <div class="pagination">
        <p><</p>
        <p>1 </p>
        <p>2 </p>
        <p>3 </p>
        <p>4 </p>
        <p>5 </p>
        <p>> </p>
      </div>
    </section><br><br>