config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions',
        passwords: 'users/passwords'
        }

  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :carts
  resources :history_address
  resources :admin_users, only:[:index]
  get "/add/disc" => "items#add_disc"
  get "/add/song" => "items#add_song"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy] do
    resources :discs
    resources :songs

    resources :categories,only: [:new, :create, :index, :update, :edit, :destroy] do
    end

  end
  root "items#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/disc.rb
class Disc < ApplicationRecord
	  belongs_to :item
	  has_many :songs, dependent: :delete_all
	  accepts_nested_attributes_for :songs
	  
end

app/models/disc_count.rb
class DiscCount < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/history_address.rb
class HistoryAddress < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	has_many :discs, dependent: :destroy
	has_many :histories
	has_many :carts
	#belongs_to :category

	attr_accessor :disc_name, :number, :song_name

 	accepts_nested_attributes_for :discs


end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/song_count.rb
class SongCount < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController


  private
def disc_params
  params.require(:disc).permit(:disc_name,songs_attributes: [:song_name,:number])
end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_admin!, except:[:index]

  def index
    @q = Item.search(params[:q])
    # @items = @q.result(distinct: true)
    @items = Item.all
    # Rails.logger.info(@items.first.category_id)
  end

  def new
    @disc_count = DiscCount.find(1)
    @disc_count.count = 1
    @disc_count.save
    @song_count = SongCount.find(196)#<=これは試行錯誤した回数です。データによって違うので、最初にコンソールで作ったIDを入れてください
    @song_count.count = 1
    @song_count.save
  	@item = Item.new
    @disc_count.count.times{
      @disc = @item.discs.build
      @song_count.count.times{@disc.songs.build}
    }
  end

  def add_disc
    @song_count = SongCount.find(196)#<=これは試行錯誤した回数です。データによって違うので、最初にコンソールで作ったIDを入れてください
    @disc_count = DiscCount.find(1)
    @disc_count.count += 1
    @disc_count.save
    @item = Item.new
    @disc_count.count.times{
      @disc = @item.discs.build
      @song_count.count.times{@disc.songs.build}
    }
    render :new
  end

  def add_song
    @song_count = SongCount.find(196)#<=これは試行錯誤した回数です。データによって違うので、最初にコンソールで作ったIDを入れてください
    @disc_count = DiscCount.find(1)
    @item = Item.new
    @song_count.count += 1
    @song_count.save
    @disc_count.count.times{
      @disc = @item.discs.build
      @song_count.count.times{@disc.songs.build}
    }
    render :new
  end

  def create
  	@item = Item.new(item_params)
    if @item.save
    redirect_to ("/")
  else
    render ("items/new")
  end
  end

  def show
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @disc = @item.discs
    @item.update(item_params)
    redirect_to ("/")
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.delete
      flash[:notice] = "削除しました。"
      redirect_to("/items")
    end
  end

  private

    def song_count_params
      params.require(:song_count).permit(:count)
    end
    def item_params
        params.require(:item).permit(
          :artist_name,
          :item_name,
          :image,
          :price,
          :label_name,
          :stock,
          :category_id,
          :release_date,
            discs_attributes: [
              :id,
              :disc_name,
              songs_attributes: [
                :id,
                :number,
                :song_name
              ]
            ]
          )
        #Rails.logger.info(params[:item][:discs_attributes].count)
    end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redpanda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="slidemenu">
      <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
        <% if admin_signed_in? %>
          <li class="">
            <%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete %>
          </li>
          <li class="">
            <%= link_to '投稿フォーム', new_item_path %>
          </li>
        <% else %>
          <li class="">
            <%= link_to "管理者ログイン", new_admin_session_path %>
          </li>
        <% end %>
      </ul>
    </div>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redpanda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <header>
    <% if admin_signed_in? #アドミンでログインしている場合のCSS設定%>
    <div class="applicaion-header-admins">
    <% else #アドミンでログインしていない場合のCSS設定 %>
    <div class="applicaion-header-users">
    <% end %>
    <div class="applicaion-header-search">
      REDPANDA　ヘッダー共通部分このへん
    </div>
      <ul>
        <% if admin_signed_in? %>
          <li><%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete %></li>
          <li><%= link_to '投稿フォーム', new_item_path %></li>
        <% elsif user_signed_in? %>
          <li>ログイン中のユーザー：<%= current_user.email %></li>
          <li>カート</li>
          <li><%= link_to 'ログアウト',destroy_user_session_path,method: :delete%></li>
        <% else %>
          <li><%= link_to 'ログイン',new_user_session_path %></li>
          <li><%= link_to 'ユーザー登録',new_user_registration_path %></li>
          <li><%= link_to "管理者ログイン あとで消す", new_admin_session_path %> admin@admin.com(adminadmin)</li>
          <li><%= link_to "管理者ユーザー作成 あとで消す", new_admin_registration_path %></li>
        <% end %>
      </ul>
    </div>
   </header>

   <%if flash[:notice]%>
     <div class="flash">　<!-- ログイン時のメッセージ格納 -->
       <%= flash[:notice] %>
     </div>
   <% end %>
   <%if flash[:alert]%>
     <div class="flash flash-alert">
       <%= flash[:alert] %>
     </div>
   <% end %>
    <%= yield %>

  </body>
</html>