config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions',
        passwords: 'users/passwords'
        }

  devise_for :users,controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
      }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :carts
  resources :history_address
  resources :admin_users, only:[:index]
  get "/add/disc" => "items#add_disc"
  get "/add/song" => "items#add_song"

  resources :items,only: [:new, :create, :index, :show, :update, :edit, :destroy] do
    resources :discs
    resources :songs

    resources :categories,only: [:new, :create, :index, :update, :edit, :destroy] do
    end

  end
  root "items#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/disc.rb
class Disc < ApplicationRecord
	  belongs_to :item
	  has_many :songs, dependent: :delete_all
	  accepts_nested_attributes_for :songs
	  
end

app/models/disc_count.rb
class DiscCount < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/history_address.rb
class HistoryAddress < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

	attachment :image
	has_many :discs, dependent: :destroy
	has_many :histories
	has_many :carts
	#belongs_to :category

	attr_accessor :disc_name, :number, :song_name

 	accepts_nested_attributes_for :discs


end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :disc
end

app/models/song_count.rb
class SongCount < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
	def index
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
   def new
  	@category = Category.new
  end

  def index
  	@category = Category.new
  	@categories = Category.all
  end

  def create
  	@category = Category.new(category_params)
    @category.save
    redirect_to ("/")
  end

  def edit
  end

  def update
  end

  def destroy
  end


  def edit
  end

private
	def category_params
	  params.require(:category).permit(:name)
	end
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController


  private
def disc_params
  params.require(:disc).permit(:disc_name,songs_attributes: [:song_name,:number])
end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_admin!, except:[:index]

  def index
    @q = Item.search(params[:q])
    # @items = @q.result(distinct: true)
    @items = Item.all
    # Rails.logger.info(@items.first.category_id)
  end

  def new
    @disc_count = DiscCount.find(1)
    @disc_count.count = 1
    @disc_count.save
    @song_count = SongCount.find(196)#<=これは試行錯誤した回数です。データによって違うので、最初にコンソールで作ったIDを入れてください
    @song_count.count = 1
    @song_count.save
  	@item = Item.new
    @disc_count.count.times{
      @disc = @item.discs.build
      @song_count.count.times{@disc.songs.build}
    }
  end

  def add_disc
    @song_count = SongCount.find(196)#<=これは試行錯誤した回数です。データによって違うので、最初にコンソールで作ったIDを入れてください
    @disc_count = DiscCount.find(1)
    @disc_count.count += 1
    @disc_count.save
    @item = Item.new
    @disc_count.count.times{
      @disc = @item.discs.build
      @song_count.count.times{@disc.songs.build}
    }
    render :new
  end

  def add_song
    @song_count = SongCount.find(196)#<=これは試行錯誤した回数です。データによって違うので、最初にコンソールで作ったIDを入れてください
    @disc_count = DiscCount.find(1)
    @item = Item.new
    @song_count.count += 1
    @song_count.save
    @disc_count.count.times{
      @disc = @item.discs.build
      @song_count.count.times{@disc.songs.build}
    }
    render :new
  end

  def create
  	@item = Item.new(item_params)
    if @item.save
    redirect_to ("/")
  else
    render ("items/new")
  end
  end

  def show
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @disc = @item.discs
    @item.update(item_params)
    redirect_to ("/")
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.delete
      flash[:notice] = "削除しました。"
      redirect_to("/items")
    end
  end

  private

    def song_count_params
      params.require(:song_count).permit(:count)
    end
    def item_params
        params.require(:item).permit(
          :artist_name,
          :item_name,
          :image,
          :price,
          :label_name,
          :stock,
          :category_id,
          :release_date,
            discs_attributes: [
              :id,
              :disc_name,
              songs_attributes: [
                :id,
                :number,
                :song_name
              ]
            ]
          )
        #Rails.logger.info(params[:item][:discs_attributes].count)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
  	@disc = Disc.new
  	@disc.songs.build
  end

  def create
  	@disc = Disc.new(item_params)
    @disc.save
    redirect_to ("/items")
  end
  
private
  def song_params
        params.require(:song).permit(:artist_name , :item_name, :image, :price, :label_name, :stock, :category_id, :release_date,discs_attributes:[:disc_name,songs_attributes:[:song_name,:number]])
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h2>カテゴリー一覧</h2>
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(categories_create_path) do |f| %>
    <h4>カテゴリー追加</h4>
    <%= f.text_field :name %>
 
    <%= f.submit '投稿' %>
 
<% end %>


<% @categories.each do |category| %>
 <%= category.name %>   <%="edit"%>   <%="destroy"%><br>
<% end %>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/discs/new.html.erb
<h1>Discs#new</h1>
<p>Find me in app/views/discs/new.html.erb</p>

app/views/items/edit.html.erb
<!-- <form> -->
<!--親要素 -->
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= @item.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>商品登録</h2><br>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group has-icon">
        アーティスト名　<%= f.text_field :artist_name, class:"form-control" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      タイトル　　　　<%= f.text_field :item_name, class:"form-control", rows:"3" %>
    </div>
  </div>
  <!--カテゴリー登録-->
      カテゴリー　　　<%= f.collection_select :category_id, Category.all, :id, :name %>
  <div class="row">
    <div class="col-sm-12">
      レーベル　　　　<%= f.text_field :label_name, class:"form-control", rows:"3" %>
    </div>
  </div>
   <div class="row">
    <div class="col-sm-12">
      価格　　　　　　<%= f.text_field :price, class:"form-control", rows:"3" %>
    </div>
  </div>
    <div class="row">
    <div class="col-sm-12">
      ジャケット画像　<%= f.attachment_field :image %>
    </div>
  </div>
  <br>
   <div class="row">
    <div class="col-sm-12">
      在庫数　　　　　<%= f.text_field :stock, class:"form-control", rows:"3" %>
    </div>
  </div>
     <div class="row">
    <div class="col-sm-12">
      リリース日　　　<%= f.text_field :release_date, class:"form-control", rows:"3" %>
    </div>
  </div>
    <!--子要素 -->

    <%= f.fields_for :discs do |d|%>
        <%# @item.discs.each do |f| %>
    ディスク番号　　<%= d.text_field :disc_name %><br>
      <!--孫要素 -->
      <%= d.fields_for :songs do |s|%>
      　　　　曲名　　<%= s.text_field :number, :size=>"5",:placeholder=> "曲順" %> <%= s.text_field :song_name,:placeholder=> "曲名" %><br>
      <% end %>
     <%# end%>
    <% end %>
  <hr>
  <%= f.submit "変更する", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
  <%= link_to"一覧に戻る", "/" %>
<% end %>
<!-- </form> 

app/views/items/index.html.erb
<h1>CD一覧<h4><%=link_to("カテゴリー編集","/categories/index")%></h4></h1>
<!--検索フォーム-->
商品検索
　<%= search_form_for @q,url: items_path do |f| %>
	  <%= f.search_field :artist_name_or_label_name_or_item_name_cont %>
	  <%= f.submit "search",class: 'record-form__submit-button' %><br><br>
  <% end %>
	<div class="container">
		<thead>
			<tr>
			<% @items.each do |item| %>
			<td><div class="item_image">
				<!--画像画面左　登録がない場合noimageを表示-->
				<%#= attachment_image_tag item, :image, :fill, 150, 150, format: 'jpeg', fallback: "noimage_panda1.jpg",class:"item_image" %></div></td>
				<!--商品内容-->
				<td><div>artist name:<%= item.artist_name %></div>
				<div>cd name:<%= item.item_name %></div>
				<div>label:<%= item.label_name %></div>
				<div>stock:<%= item.stock %></div>
				<div>price:￥<%= item.price %></div>
				<%=link_to("編集する","/items/#{item.id}/edit")%><br>
				<%=link_to "削除する", item_path(item.id), method: :delete, "data-confirm" => '削除してよろしいですか？' %><br>
			<% end %></td>
			</div>
		</div>
	</div>
</tr>
</thead><br><br>

app/views/items/new.html.erb
<!-- <form> -->
<!--親要素 -->
<%= form_for(@item, url: items_path) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= @item.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>商品登録</h2>
  <div class="row">
  　<div class="col-sm-12">
      ジャケット画像　<%= f.attachment_field :image %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <div class="form-group has-icon">
        アーティスト名　<%= f.text_field :artist_name, class:"form-control" %>
        <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
      </div>
    </div>
    <div class="col-sm-6">
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      タイトル　　　　<%= f.text_field :item_name, class:"form-control", rows:"3" %>
    </div>
  </div>
  <!--カテゴリー登録-->
      カテゴリー　　　<%= f.collection_select :category_id, Category.all, :id, :name %>
  <div class="row">
    <div class="col-sm-12">
      レーベル　　　　<%= f.text_field :label_name, class:"form-control", rows:"3" %>
    </div>
  </div>
   <div class="row">
    <div class="col-sm-12">
      価格　　　　　　<%= f.text_field :price, class:"form-control", rows:"3" %>
    </div>
  </div>
  <br>
   <div class="row">
    <div class="col-sm-12">
      在庫数　　　　　<%= f.text_field :stock, class:"form-control", rows:"3" %>
    </div>
  </div>
     <div class="row">
    <div class="col-sm-12">
      リリース日　　　<%= f.text_field :release_date, class:"form-control", rows:"3" %>
    </div>
  </div>
    <!--子要素 -->
    <%= f.fields_for :discs do |d|%>
    ディスク番号　　<%= d.text_field :disc_name %><br>
      <!--孫要素 -->
      <%= d.fields_for :songs do |s|%>
      　　　　　　　　<%= s.text_field :number, :size=>"5",:placeholder=> "曲順" %> <%= s.text_field :song_name,:placeholder=> "曲名" %><br>
      <% end %>
    <% end %>
    <%= link_to "ディスク追加", add_disc_path %>
    <%= link_to "ソング追加", add_song_path %>
    <%= link_to "リセット", new_item_path %>
  <hr>
  <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
  <%= link_to"一覧に戻る", "/" %>
<% end %>
<!-- </form> 

app/views/items/show.html.erb
<h1>Items#show</h1>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>